/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat10;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Lester
 */
public class ClientGUI3 extends javax.swing.JFrame {

    private Client client;
    
    private String defaultHost, name;
    private int defaultPort;
    private boolean connected;
    
    /**
     * Creates new form NewJFrame
     */
    public ClientGUI3(String user) {
        initComponents();
        
        name = user;
        
        sendButton.setEnabled(false);
        msgField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatScreen = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgField = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        tfPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfServer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginLogout = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        userList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatScreen.setEditable(false);
        chatScreen.setColumns(20);
        chatScreen.setLineWrap(true);
        chatScreen.setRows(5);
        chatScreen.setWrapStyleWord(true);
        jScrollPane1.setViewportView(chatScreen);

        msgField.setColumns(20);
        msgField.setLineWrap(true);
        msgField.setRows(5);
        msgField.setWrapStyleWord(true);
        jScrollPane2.setViewportView(msgField);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        tfPort.setText("1500");

        jLabel1.setText("Port");

        tfServer.setText("192.168.2.15");

        jLabel2.setText("Server");

        jLabel3.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        jLabel3.setText("Chat10");

        loginLogout.setText("Login");
        loginLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginLogoutActionPerformed(evt);
            }
        });

        userList.setEditable(false);
        userList.setColumns(20);
        userList.setLineWrap(true);
        userList.setRows(5);
        userList.setWrapStyleWord(true);
        jScrollPane3.setViewportView(userList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(loginLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfServer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(loginLogout)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginLogoutActionPerformed
        // TODO add your handling code here:
        if (loginLogout.getText() == "Login") { // press to login
            // Username passed from LoginDB
            String uname = name;
            
            defaultHost = tfServer.getText().trim();
            defaultPort = Integer.parseInt(tfPort.getText().trim());
            
            // do nothing if either field is empty
            if (defaultHost.length() == 0 || defaultPort < 0) {
                return;
            }
            
            client = new Client(defaultHost, defaultPort, uname, this);
            
            if(!client.start()) {
                return;
            }
            
            loginLogout.setText("Logout");
            tfServer.setEditable(false);
            tfPort.setEditable(false);
            sendButton.setEnabled(true);
            msgField.setEnabled(true);
            connected = true;
        } else { // press to logout
            loginLogout.setText("Login");
            tfServer.setEditable(true);
            tfPort.setEditable(true);
            sendButton.setEnabled(false);
            msgField.setEnabled(false);
            
            client.sendMessage(new ChatMessage(ChatMessage.LOGOUT, ""));
        }
    }//GEN-LAST:event_loginLogoutActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        client.sendMessage(new ChatMessage(ChatMessage.MESSAGE, msgField.getText()));
        msgField.setText("");
        return;
//        if (msgField.getText().length() == 0) {
//            return;
//        }
//        else {
//            String str = msgField.getText();
//            chatScreen.append(str + "\n");
//            msgField.setText("");
//        }
    }//GEN-LAST:event_sendButtonActionPerformed

    void append(String str) {
        chatScreen.append(str);
        chatScreen.setCaretPosition(chatScreen.getText().length() - 1);
    }
    
    void connectionFailed() {
        // login.setEnabled(true);
        // logout.setEnabled(false);
        // whoIsIn.setEnabled(false);
        // label.setText("Enter your username below");
        // tf.setText("Anonymous");
        // // reset port number and host name as a construction time
        // tfPort.setText("" + defaultPort);
        // tfServer.setText(defaultHost);
        // // let the user change them
        // tfServer.setEditable(false);
        // tfPort.setEditable(false);
        // // don't react to a <CR> after the username
        // tf.removeActionListener(this);
        connected = false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        String a = args[0];
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI3(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loginLogout;
    private javax.swing.JTextArea msgField;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfServer;
    private javax.swing.JTextArea userList;
    // End of variables declaration//GEN-END:variables
}
